import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import { LayoutProps } from '@/types/page';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lab1",
  description: "Generated by Gamarska Daria",
};

export default function RootLayout({
                                     children,
                                   }: LayoutProps) {
  return (
      <html lang="en">
      <body className={inter.className}>{children}</body>
      </html>
  );
}